### ISSUE TITLE
Html code doesn't work in author fields

### ISSUE THREAD

**Issue by vokai** [mercuree/html-telegraph-poster#1]
Hi! This is best poster for telegraph but I have seen that if I use <a href="" ecc >author</a> It give me html code in my post and not url to website.

url = 'http://.... '
writer = '<a href="' + url + '">john johnson</a>'
t = TelegraphPoster()
result = t.post(title=titolo, author=writer, text=testo)
Am I wrong doing something wrong?

P.S. In text field hypertext url works fine.

**Comment by mercuree** [comment]
Just ran your code and got this result:
http://telegra.ph/titolo-09-04-2
Which version of python are you using?

**Comment by vokai** [comment]
I use 2.7 version. I used example code in my first message, with a real url the "author" field doesn't become hypertext.

**Comment by mercuree** [comment]
Sorry, i didn't mention in the docs, use author_url to set url
```python
result = t.post(title=titolo, author=writer, text=testo, author_url="http://example.com")
```

**Comment by vokai** [comment]
I'm going to try...But for post image in "text" area I need to upload it before right?
