### ISSUE TITLE
Option to auto upload images

### ISSUE THREAD

**Issue by NullPointerMaker** [mercuree/html-telegraph-poster#11]
Is it a good idea to add a parameter option `auto_upload_images`:  
When this parameter is used, the images in the `<img>` tag will be automatically uploaded and the URLs will be replaced.

**Comment by mercuree** [comment]
It's a good idea, when all of your `<img>` tags have full url. But what should we do if urls are relative? Then you should pass another option with base url or try to find it in inside input html. 
I think it can be implemented in a separate module. If you have idea how to implement this feature, I would appreciate any help

**Comment by NullPointerMaker** [comment]
Okay, I will try to implement it.

If they are relative URLs, we first get the base URL from the parameter `base`. If it is not found, try to get from `<base>`, if not, we will return the original HTML text, or should we raise an exception?

And what do you think this module should be named?

**Comment by mercuree** [comment]
Ok, so I made some initial work. Check it out #12 
You can implement threading for image uploading, if you wish.
I think, missing base_url should not raise any exception. Images, that have relative paths and no base_url, will be remove from document silently. Maybe we can put some warning messages.
There is still one performance issue, because you get html back, and then TelegraphPoster will parse it again. 
Simple usage (also see tests)
```python
from html_telegraph_poster.utils import DocumentPreprocessor
dp = DocumentPreprocessor(html_string)
dp.upload_all_images()
dp.get_processed_html() // this should return html string with uploaded and replaced image urls
```

**Comment by NullPointerMaker** [comment]
Nice job!

And if you think parsing twice is a problem, we can also provide the option of returning document object, and pass it to main module.  
But I don't think this is a big problem. Only in the case of multiple concurrency will there be serious performance problems. Before that, the telegraph server may refuse service first.

**Comment by mercuree** [comment]
Ok, a little summary:
* `upload_all_images` now ignores images with telegra.ph and graph.org domains (did i forget any?)
* any upload exceptions will be ignored by default (log message with traceback will appear if logging is enabled). <br> If you want to change this behavior, you can override `DocumentPreprocessor.upload_image method`
* images are uploaded via threads, however I'm not sure if it gives any speed-up

What do you think? Is it already useful?
Changes are here #12

**Comment by NullPointerMaker** [comment]
Works great. There should be no other problems.

Thanks for your work.
