### ISSUE TITLE
Allow <br> tags in text

### ISSUE THREAD

**Issue by SyberiaK** [mercuree/html-telegraph-poster#22]
When you post a text with `<br>`s in it, TelegraphPoster just ignores them.

**Comment by mercuree** [comment]
Hi, Can you provide html example?

**Comment by SyberiaK** [comment]
Got this example:
```html
<h3>Hello world!</h3> <br>
<h4>Here we test our <br> breaks</h4>
<h4>Because they act really strange...</h4>
```

Expected behavior:
![image](https://github.com/mercuree/html-telegraph-poster/assets/97897772/8106c5e0-36ef-4792-9603-0bd4a2f1c4cc)

Actual behavior:
![image](https://github.com/mercuree/html-telegraph-poster/assets/97897772/4056f619-b2c9-40c0-8790-d4baa8588a55)

**Comment by mercuree** [comment]
Short answer:
Pass parameter clean_html=False
```python
TelegraphPoster(use_api=True,  clean_html=False)
```
Long answer:
Telegraph API accepts json formatted markup, there is no `<br>` tag. To make line break I need to send `\n`. It works inside paragraphs `<p>` and some other tags, but not in header tags `<h3>`, `<h4>`. If you send `<br>` tag inside `<h3>` instead, Telegraph will interpret it as a new empty header element as seen in your screenshots. They are all separated header elements, not just one with line breaks, therefore you can see a huge space between them.
Also my library makes some optimizations with markup. It works by default, but with `clean_html=False` you can turn it off.
