### ISSUE TITLE
Why doesn't the page I generated support instant view?

### ISSUE THREAD

**Issue by JohnChu101** [mercuree/html-telegraph-poster#6]
The page I generated doesn't support instant view (there's no button in the message)

**Comment by mercuree** [comment]
Send me that page so i can see why it doesn't work

**Comment by JohnChu101** [comment]
http://jcurl.tk/mtele

Sorry i need to use a URL shortener to avoid disclosing too much information.

**Comment by JohnChu101** [comment]
https://demos3.softaculous.com/YOURLS1b8qmbxmek/1

**Comment by JohnChu101** [comment]
I see where the problem lies in.
The newspaper library extracted invalid top_image. In my case it extracted a favicon. And it's necessary for a standard instant view telegraph.
I tried another case (a webpage from another article) still this case.
How did you solve this problem?

**Comment by JohnChu101** [comment]
And how to upload images inside the html?

**Comment by mercuree** [comment]
Ok, the problem is on newspaper side. Instant View has image limitations by size and aspect ratio. Too small or too big images can break instant view (images like 500x10px can also break instant view), so you need to remove them or replace with appropriate image

**Comment by JohnChu101** [comment]
@mercuree 
ok i wrote a method to judge whether the image is available and solved the problem.
Thanks.
