### ISSUE TITLE
Article updated instead of posted

### ISSUE THREAD

**Issue by JohnChu101** [mercuree/html-telegraph-poster#7]
I always use post method to post new articles. but very often my old post (previous one) is updated, instead of being posted as a new article with new link.

**Comment by mercuree** [comment]
This is probably an incorrect behavior and can be changed in future.
For now you have to create `TelegraphPoster` instance every time you want to post a new page.

**Comment by JohnChu101** [comment]
my code:
```
from html_telegraph_poster import TelegraphPoster
t = TelegraphPoster(access_token=access_token)
t.post(title="AAA", author='oo', author_url='http://reuters.com', text='<br><br><em>AAA</em>')
{'path': 'AAA-08-14', 'url': 'http://telegra.ph/AAA-08-14'}
t.post(title="BBB", author='op', author_url='http://reuters.com', text='<br><br><em>BBB</em>')
{'path': 'AAA-08-14', 'url': 'http://telegra.ph/AAA-08-14'}
```

@mercuree ok i see!
